In [1]:
import numpy as np

## Start with the first array

In [42]:
A = np.array([[1,2,1], [3,8,1], [0,4,1]])  
A

array([[1, 2, 1],
       [3, 8, 1],
       [0, 4, 1]])

## first pivot point subtraction

In [43]:
E_21 = np.array([[1,0,0], [-3,1,0], [0,0,1]])  
E_21

array([[ 1,  0,  0],
       [-3,  1,  0],
       [ 0,  0,  1]])

In [45]:
U_1 = E_21.dot(A)
U_1

array([[ 1,  2,  1],
       [ 0,  2, -2],
       [ 0,  4,  1]])

## Elimination matrix Second pivot point

In [46]:
E_32 = np.array([[1,0,0], [0,1,0], [0,-2,1]])  
E_32

array([[ 1,  0,  0],
       [ 0,  1,  0],
       [ 0, -2,  1]])

In [47]:
U = E_32.dot(U_1)
U

array([[ 1,  2,  1],
       [ 0,  2, -2],
       [ 0,  0,  5]])

## Put together
`E_32 * E_31 * A = U`

`E = E_32 * E31`

In [49]:
E = E_32.dot(E_21)
E

array([[ 1,  0,  0],
       [-3,  1,  0],
       [ 6, -2,  1]])

In [50]:
E.dot(A)

array([[ 1,  2,  1],
       [ 0,  2, -2],
       [ 0,  0,  5]])

### Another example

In [52]:
A = np.array([[2,5,1], [4,-4,0], [0,7,4]])  
E_21 = np.array([[1,0,0], [-2,1,0], [0,0,1]])  

u_mid = E_21.dot(A)
u_mid

array([[  2,   5,   1],
       [  0, -14,  -2],
       [  0,   7,   4]])

In [53]:
E_32 = np.array([[1,0,0], [0,1,0], [0,1,2]])  

u = E_32.dot(u_mid)
u

array([[  2,   5,   1],
       [  0, -14,  -2],
       [  0,   0,   6]])

In [54]:
E_32.dot(E_21)

array([[ 1,  0,  0],
       [-2,  1,  0],
       [-2,  1,  2]])