In [2]:
import numpy as np

## Start with the first array

In [42]:
A = np.array([[1,2,1], [3,8,1], [0,4,1]])  
A

array([[1, 2, 1],
       [3, 8, 1],
       [0, 4, 1]])

## first pivot point subtraction

In [43]:
E_21 = np.array([[1,0,0], [-3,1,0], [0,0,1]])  
E_21

array([[ 1,  0,  0],
       [-3,  1,  0],
       [ 0,  0,  1]])

In [45]:
U_1 = E_21.dot(A)
U_1

array([[ 1,  2,  1],
       [ 0,  2, -2],
       [ 0,  4,  1]])

## Elimination matrix Second pivot point

In [46]:
E_32 = np.array([[1,0,0], [0,1,0], [0,-2,1]])  
E_32

array([[ 1,  0,  0],
       [ 0,  1,  0],
       [ 0, -2,  1]])

In [47]:
U = E_32.dot(U_1)
U

array([[ 1,  2,  1],
       [ 0,  2, -2],
       [ 0,  0,  5]])

## Put together
`E_32 * E_31 * A = U`

`E = E_32 * E31`

In [49]:
E = E_32.dot(E_21)
E

array([[ 1,  0,  0],
       [-3,  1,  0],
       [ 6, -2,  1]])

In [50]:
E.dot(A)

array([[ 1,  2,  1],
       [ 0,  2, -2],
       [ 0,  0,  5]])

### Another example

In [52]:
A = np.array([[2,5,1], [4,-4,0], [0,7,4]])  
E_21 = np.array([[1,0,0], [-2,1,0], [0,0,1]])  

u_mid = E_21.dot(A)
u_mid

array([[  2,   5,   1],
       [  0, -14,  -2],
       [  0,   7,   4]])

In [53]:
E_32 = np.array([[1,0,0], [0,1,0], [0,1,2]])  

u = E_32.dot(u_mid)
u

array([[  2,   5,   1],
       [  0, -14,  -2],
       [  0,   0,   6]])

In [54]:
E_32.dot(E_21)

array([[ 1,  0,  0],
       [-2,  1,  0],
       [-2,  1,  2]])

## Multiplication

In [57]:
A = np.array([[4],[2],[3]]) 
A

array([[4],
       [2],
       [3]])

In [58]:
B = np.array([[1,8,2]])  
B

array([[1, 8, 2]])

In [59]:
A.dot(B)

array([[ 4, 32,  8],
       [ 2, 16,  4],
       [ 3, 24,  6]])

In [66]:
B.dot(A)

array([[26]])

### Blocks

In [69]:
Q = np.random.randint(0, 9, size=(6,6))
P = np.random.randint(0, 9, size=(6,6))
Q, P

(array([[0, 3, 8, 5, 7, 8],
        [1, 3, 7, 1, 4, 5],
        [0, 2, 4, 0, 1, 3],
        [6, 6, 3, 1, 7, 5],
        [0, 3, 6, 2, 3, 7],
        [8, 6, 3, 2, 2, 4]]),
 array([[2, 2, 8, 4, 3, 7],
        [5, 1, 6, 7, 4, 5],
        [3, 2, 7, 8, 8, 7],
        [0, 8, 6, 7, 3, 8],
        [6, 4, 1, 5, 8, 2],
        [1, 1, 8, 1, 8, 0]]))

In [76]:
C = Q.dot(P)
C

array([[ 89,  95, 175, 163, 211, 125],
       [ 67,  48, 125, 113, 146,  87],
       [ 31,  17,  65,  54,  72,  40],
       [ 98,  65, 158, 137, 165, 115],
       [ 58,  50, 131, 105, 146,  79],
       [ 71,  56, 167, 126, 126, 127]])

In [78]:
q_1 = Q[:3,:3]
q_2 = Q[:3,3:]
q_3 = Q[3:,:3]
q_4 = Q[3:,3:]

p_1 = P[:3,:3]
p_2 = P[:3,3:]
p_3 = P[3:,:3]
p_4 = P[3:,3:]

c_1 = C[:3,:3]
c_2 = C[:3,3:]
c_3 = C[3:,:3]
c_4 = C[3:,3:]


In [85]:
# top left
np.array_equal(q_1.dot(p_1) + q_2.dot(p_3),c_1)

True

In [89]:
# top right
np.array_equal(q_1.dot(p_2) + q_2.dot(p_4),c_2)

True

In [90]:
# bottom left
np.array_equal(q_3.dot(p_1) + q_4.dot(p_3),c_3)

True

In [91]:
# bottom right
np.array_equal(q_3.dot(p_2) + q_4.dot(p_4),c_4)

True

### Inverse

In [126]:
A = np.array([[2,5], [3,4]])  
A

array([[2, 5],
       [3, 4]])

In [134]:
A_inv = np.array([[-4/7,5/7], [3/7,-2/7]])  
A_inv

array([[-0.57142857,  0.71428571],
       [ 0.42857143, -0.28571429]])

In [133]:
A.dot(A_inv)

array([[-1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00, -1.00000000e+00]])

In [139]:
c = np.array([[1,3,1], [1,-2,-1], [2,1,2]])  
d = np.array([[3/10,1/2,1/10], [2/5,0,-1/5], [-1/2,-1/2,1/2]])  

d.dot(c)

array([[ 1.00000000e+00, -8.32667268e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [141]:
d

array([[ 0.3,  0.5,  0.1],
       [ 0.4,  0. , -0.2],
       [-0.5, -0.5,  0.5]])

In [137]:
np.linalg.inv(c)

array([[ 0.3,  0.5,  0.1],
       [ 0.4, -0. , -0.2],
       [-0.5, -0.5,  0.5]])

### Trying to do things fully matrix

In [10]:
a = np.array([[1,3,1], 
              [1,-2,-1], 
              [2,1,2]])  

a

array([[ 1,  3,  1],
       [ 1, -2, -1],
       [ 2,  1,  2]])

### Eliminate column 1

In [19]:
# 1: -1*row1 + row 2
e1 = np.array([[1,0,0], 
               [-1,1,0], 
               [0,0,1]])  
a1 = e1.dot(a)
print('a1\n', a1)

# 2: -2*row1 + row 3
e2 = np.array([[1,0,0], 
               [0,1,0], 
               [-2,0,1]])  
a2 = e2.dot(a1)
print('a2\n', a2)


# 3: swap row 2 & 3
e3 = np.array([[1,0,0], 
               [0,0,1], 
               [0,1,0]])  
a3 = e3.dot(a2)
print('a3\n', a3)

# 4: -1* r2 + r3
e4 = np.array([[1,0,0], 
               [0,1,0], 
               [0,-1,1]])  
a4 = e4.dot(a3)
print('a4\n', a4)

# 5: r2/-5 aka * 1/-5 
#    r3/-2 aka * 1/-2
e5 = np.array([[1,0,0], 
               [0,-1/5,0], 
               [0,0,-1/2]])  
a5 = e5.dot(a4)
print('a5\n', a5)

# 6: -3*r2 + r1
#    -1*r3 + r1
e6 = np.array([[1,-3,-1], 
               [0,1,0], 
               [0,0,1]])  
a6 = e6.dot(a5)
print('a6\n', a6)

a1
 [[ 1  3  1]
 [ 0 -5 -2]
 [ 2  1  2]]
a2
 [[ 1  3  1]
 [ 0 -5 -2]
 [ 0 -5  0]]
a3
 [[ 1  3  1]
 [ 0 -5  0]
 [ 0 -5 -2]]
a4
 [[ 1  3  1]
 [ 0 -5  0]
 [ 0  0 -2]]
a5
 [[1. 3. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
a6
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
e6.dot(e5.dot(e4.dot(e3.dot(e2.dot(e1)))))

array([[ 0.3,  0.5,  0.1],
       [ 0.4,  0. , -0.2],
       [-0.5, -0.5,  0.5]])

### Rectangle matrix

In [25]:
a = np.array([[1,2,2,2], 
              [2,4,6,8], 
              [3,6,8,10]])  

# 1: -1*row1 + row 2

e = np.array([[1,0,0], 
              [0,1,0], 
              [0,0,1]])  


e.dot(a)

array([[ 1,  2,  2,  2],
       [ 2,  4,  6,  8],
       [ 3,  6,  8, 10]])

In [34]:
e1 = np.array([[1,0,0], 
               [-2,1,0], 
               [-3,0,1]])  

e2 = np.array([[1,0,0], 
               [0,1,0], 
               [0,-1,1]])  

# row echelon form
print(e2.dot(e1.dot(a)))

# reduced row echelon form (0 above and below pivot)
e3 = np.array([[1,-1,0], 
               [0,1/2,0], 
               [0,0,1]])  
print(e3.dot(e2.dot(e1.dot(a))))

[[1 2 2 2]
 [0 0 2 4]
 [0 0 0 0]]
[[ 1.  2.  0. -2.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  0.]]


In [37]:
e3.dot(e2.dot(e1))

array([[ 3. , -1. ,  0. ],
       [-1. ,  0.5,  0. ],
       [-1. , -1. ,  1. ]])

## Transpose

In [39]:
at = a.T

at

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 2,  6,  8],
       [ 2,  8, 10]])

In [59]:
e1 = np.array([[1,0,0,0], 
              [-2,1,0,0], 
              [-2,0,1,0],
              [-2,0,0,1]])  

e2 = np.array([[1,0,0,0], 
              [0,1,0,0], 
              [0,0,1/2,0],
              [0,0,-2,1]]) 

e3 = np.array([[1,0,-2,0], 
              [0,1,0,0], 
              [0,0,1,0],
              [0,0,0,1]]) 

e3.dot(e2.dot(e1.dot(at)))

array([[1., 0., 1.],
       [0., 0., 0.],
       [0., 1., 1.],
       [0., 0., 0.]])

In [60]:
e3.dot(e2.dot(e1))

array([[ 3. ,  0. , -1. ,  0. ],
       [-2. ,  1. ,  0. ,  0. ],
       [-1. ,  0. ,  0.5,  0. ],
       [ 2. ,  0. , -2. ,  1. ]])

## Projections

In [6]:
a = np.array([[1,0,0], 
              [0,1,0], 
              [0,0,1],
              [0,0,0]])  
a.dot(a.T.dot(a)).dot(a.T)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [7]:
b = np.array([[1],[2],[3],[4]])

a.dot(a.T.dot(a)).dot(a.T).dot(b)

array([[1],
       [2],
       [3],
       [0]])

## Scratch

In [5]:
a = np.array([[1,1,1]]).T

a.T.dot(a)

array([[3]])

In [18]:
a = np.array([[1,-1,0,0]]).T
b = np.array([[0,1,-1,0]]).T
c = np.array([[0,0,1,-1]]).T


B = b-(a.T.dot(b)/a.T.dot(a))*a
B

array([[ 0.5],
       [ 0.5],
       [-1. ],
       [ 0. ]])

In [16]:
B.T.dot(B)

array([[1.5]])

In [21]:
B.T.dot(c)

array([[-0.66666667]])

In [27]:
C = c - ((a.T.dot(c)/a.T.dot(a))* a) - ((B.T.dot(c)/B.T.dot(B))* B)
C

array([[ 0.33333333],
       [ 0.33333333],
       [ 0.33333333],
       [-1.        ]])

In [45]:
Q = np.hstack((a/(2**(1/2)),B/((3/2)**(1/2)),C/((4/3)**(1/2))))

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -3.88527392e-17],
       [ 0.00000000e+00, -3.88527392e-17,  1.00000000e+00]])

In [ ]:
a = np.array([[1,-1,0,0]])
b = np.array([[0,1,-1,0]]).T
c = np.array([[0,0,1,-1]]).T

In [10]:
np.ones((2,3,16)).dot(np.ones((16,4))).shape

(3, 4)

## Scratch Support

In [44]:
a = np.array([[1, 2, 3]]
        )

b = np.array([[1, 2, 3],
         [1, 2, 3],
         [0.0030, 0.0040, 0.0050],
         [0.0040, 0.0050, 0.0060]])

In [48]:
b.T.shape,b.T

((3, 4),
 array([[1.   , 1.   , 0.003, 0.004],
        [2.   , 2.   , 0.004, 0.005],
        [3.   , 3.   , 0.005, 0.006]]))

In [49]:
a

array([[1, 2, 3]])

In [46]:
a.dot(b.T)

array([[14.   , 14.   ,  0.026,  0.032]])